definitions:
  main.Order:
    properties:
      book_uuid:
        type: integer
      description:
        type: string
      uuid:
        type: integer
    type: object
info:
  contact: {}
paths:
  /create-order:
    post:
      description: allows to buy a book and return the information about it
      operationId: create-order
      parameters:
      - description: Book uuid
        in: formData
        name: book_uuid
        required: true
        type: integer
      - description: Author name
        in: formData
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
      summary: Created an order
  /paginate/{page_number}:
    get:
      consumes:
      - application/json
      description: allows to show all pages by page number
      operationId: paginate
      parameters:
      - description: Page number
        in: path
        name: page_number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
      summary: Show order by page number
  /show/{order_uuid}:
    get:
      consumes:
      - application/json
      description: shows the basic information about the specific order
      operationId: get-order-data
      parameters:
      - description: Order uuid
        in: path
        name: order_uuid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Order'
      summary: Get the specific order data
swagger: "2.0"
